@file:Suppress("unused")

package com.tradiebot.cythero.app.theme

import androidx.compose.ui.graphics.Color

val cythero_theme_light_primary = Color(0xFF58A85F)
val cythero_theme_light_onPrimary = Color(0xFFFFFFFF)
val cythero_theme_light_primaryContainer = Color(0xFFDAEC73)
val cythero_theme_light_onPrimaryContainer = Color(0xFF191E00)
val cythero_theme_light_secondary = Color(0xFF5D6145)
val cythero_theme_light_onSecondary = Color(0xFFFFFFFF)
val cythero_theme_light_secondaryContainer = Color(0xFFE2E5C2)
val cythero_theme_light_onSecondaryContainer = Color(0xFF1A1D07)
val cythero_theme_light_tertiary = Color(0xFF3B665B)
val cythero_theme_light_onTertiary = Color(0xFFFFFFFF)
val cythero_theme_light_tertiaryContainer = Color(0xFFBDECDE)
val cythero_theme_light_onTertiaryContainer = Color(0xFF00201A)
val cythero_theme_light_error = Color(0xFFBA1A1A)
val cythero_theme_light_errorContainer = Color(0xFFFFDAD6)
val cythero_theme_light_onError = Color(0xFFFFFFFF)
val cythero_theme_light_onErrorContainer = Color(0xFF410002)
val cythero_theme_light_background = Color(0xFFF3F4F6)
val cythero_theme_light_onBackground = Color(0xFF1F2937)
val cythero_theme_light_surface = Color(0xFFF3F4F6)
val cythero_theme_light_onSurface = Color(0xFF1F2937)
val cythero_theme_light_surfaceVariant = Color(0xFFE4E3D2)
val cythero_theme_light_onSurfaceVariant = Color(0xFF47483B)
val cythero_theme_light_outline = Color(0xFF77786A)
val cythero_theme_light_inverseOnSurface = Color(0xFFF3F1E8)
val cythero_theme_light_inverseSurface = Color(0xFF31312B)
val cythero_theme_light_inversePrimary = Color(0xFFBED05B)
val cythero_theme_light_shadow = Color(0xFF000000)
val cythero_theme_light_surfaceTint = Color(0xFF58A85F)
val cythero_theme_light_outlineVariant = Color(0xFFC8C7B7)
val cythero_theme_light_scrim = Color(0xFF000000)

val cythero_theme_dark_primary = Color(0xFF87D98A)
val cythero_theme_dark_onPrimary = Color(0xFF003910)
val cythero_theme_dark_primaryContainer = Color(0xFF00531A)
val cythero_theme_dark_onPrimaryContainer = Color(0xFFA2F6A4)
val cythero_theme_dark_secondary = Color(0xFFB9CCB4)
val cythero_theme_dark_onSecondary = Color(0xFF243424)
val cythero_theme_dark_secondaryContainer = Color(0xFF3A4B39)
val cythero_theme_dark_onSecondaryContainer = Color(0xFFD5E8D0)
val cythero_theme_dark_tertiary = Color(0xFFA1CED5)
val cythero_theme_dark_onTertiary = Color(0xFF00363C)
val cythero_theme_dark_tertiaryContainer = Color(0xFF1F4D53)
val cythero_theme_dark_onTertiaryContainer = Color(0xFFBCEBF2)
val cythero_theme_dark_error = Color(0xFFFFB4AB)
val cythero_theme_dark_errorContainer = Color(0xFF93000A)
val cythero_theme_dark_onError = Color(0xFF690005)
val cythero_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val cythero_theme_dark_background = Color(0xFF1F2937)
val cythero_theme_dark_onBackground = Color(0xFFE2E3DD)
val cythero_theme_dark_surface = Color(0xFF1F2937)
val cythero_theme_dark_onSurface = Color(0xFFE2E3DD)
val cythero_theme_dark_surfaceVariant = Color(0xFF424940)
val cythero_theme_dark_onSurfaceVariant = Color(0xFFC2C9BD)
val cythero_theme_dark_outline = Color(0xFF8C9388)
val cythero_theme_dark_inverseOnSurface = Color(0xFF1F2937)
val cythero_theme_dark_inverseSurface = Color(0xFFE2E3DD)
val cythero_theme_dark_inversePrimary = Color(0xFF58A85F)
val cythero_theme_dark_shadow = Color(0xFF000000)
val cythero_theme_dark_surfaceTint = Color(0xFF87D98A)
val cythero_theme_dark_outlineVariant = Color(0xFF424940)
val cythero_theme_dark_scrim = Color(0xFF000000)

val seed = Color(0xFFA6B745)
val seedDark = Color(0xFF58A85F)
